doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            VehiclePositionStatusEnum: App\Lib\Enum\VehiclePositionStatusEnum
            StopRequestStatusEnum: App\Lib\Enum\StopRequestStatusEnum

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            loggable:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.project_dir%/vendor/gedmo/doctrine-extensions/src/Loggable/Entity"
        
        dql:
            numeric_functions:
                acos: DoctrineExtensions\Query\Mysql\Acos
                cos: DoctrineExtensions\Query\Mysql\Cos
                radians: DoctrineExtensions\Query\Mysql\Radians
                sin: DoctrineExtensions\Query\Mysql\Sin
            string_functions:
                md5: DoctrineExtensions\Query\Mysql\Md5
                group_concat: DoctrineExtensions\Query\Mysql\GroupConcat
