# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    app.component.servicedatasync.timezone: '%env(SERVICEDATA_TIMEZONE)%'

    app.component.servicedatasync.vehicle_location_mode: '%env(SERVICEDATA_VEHICLE_LOCATION_MODE)%'

    app.component.servicedatasync.static: '%env(SERVICEDATA_STATIC_SYNC)%'
    app.component.servicedatasync.vehicleposition: '%env(SERVICEDATA_VEHICLEPOSITION_SYNC)%'
    app.component.servicedatasync.shape.middle_points_interpolation: '%env(SERVICEDATA_SHAPE_MIDDLE_POINTS_INTERPOLATION_METERS)%'

    app.gtfs.static.url: '%env(GTFS_STATIC_URL)%'
    app.gtfs.rt.url: '%env(GTFS_RT_URL)%'
    app.component.notifications.connector: '%env(NOTIFICATION_SERVICE)%'
    app.FCM.project: '%env(FCM_PROJECT)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    Gedmo\Loggable\LoggableListener:
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]

    App\EventListener\NotificationVehiclePositionSubscriber:
        tags:
            -name: 'doctrine.event_subscriber'

    App\EventListener\StopRequestVehiclePositionSubscriber:
        tags:
            -name: 'doctrine.event_subscriber'

    App\EventListener\VehicleInternalStatusDetectorSuscriber:
        tags:
            -name: 'doctrine.event_subscriber'
